#!/usr/bin/env bash
# Bash script that Install nginx on your web-01 server and requirements
apt-get update
apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
echo -e "Hello World!" > /var/www/html/index.html
sudo service nginx restart
